/* eslint-disable no-restricted-globals */
// src/service-worker.js
// Service Worker for gearbox-app PWA offline support
// CRA 5 + Workbox InjectManifest: self.__WB_MANIFEST is injected at build time

import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

clientsClaim();

// Precache all assets generated by the build (JS, CSS, HTML, etc.)
// self.__WB_MANIFEST is replaced by Workbox InjectManifest with the actual file list
precacheAndRoute(self.__WB_MANIFEST);

// App shell: for SPA navigation requests, serve index.html from precache
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  ({ request, url }) => {
    if (request.mode !== 'navigate') return false;
    if (url.pathname.startsWith('/_')) return false;
    if (url.pathname.match(fileExtensionRegexp)) return false;
    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// Static assets not in precache (e.g. lazy-loaded chunks, CDN fallbacks): cache-first
registerRoute(
  ({ url }) => url.origin === self.location.origin &&
    url.pathname.match(/\.(js|css|woff2?|ttf|eot)$/),
  new CacheFirst({
    cacheName: 'gearbox-static-v43',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 200, maxAgeSeconds: 30 * 24 * 60 * 60 }),
    ],
  })
);

// Images: cache-first with size limit
registerRoute(
  ({ url }) => url.origin === self.location.origin &&
    url.pathname.match(/\.(png|jpg|jpeg|gif|svg|ico|webp)$/),
  new CacheFirst({
    cacheName: 'gearbox-images-v43',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 30 * 24 * 60 * 60 }),
    ],
  })
);

// Allow skip-waiting via message from the app
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }

  // Clear all caches on request
  if (event.data && event.data.type === 'CLEAR_CACHE') {
    caches.keys().then(keys =>
      Promise.all(keys.map(k => caches.delete(k)))
    ).then(() => {
      event.ports[0]?.postMessage({ success: true });
    }).catch(() => {
      event.ports[0]?.postMessage({ success: false });
    });
  }

  // Report cache size
  if (event.data && event.data.type === 'GET_CACHE_SIZE') {
    caches.keys().then(async keys => {
      let totalEntries = 0;
      for (const key of keys) {
        const cache = await caches.open(key);
        const requests = await cache.keys();
        totalEntries += requests.length;
      }
      event.ports[0]?.postMessage({ size: { caches: keys.length, entries: totalEntries } });
    }).catch(() => {
      event.ports[0]?.postMessage({ size: null });
    });
  }
});
